config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  get '/profile', to: 'pages#profile', as: 'profile'

  resources :awards, except: [:show]

  resources :categories, only: [:show] do
    collection do
      get 'map'
    end
    get '/map', to: 'meals#map'
    resources :meals, only: [:show, :index] do
      resources :awards, only: [:new, :create]
    end
  end

  get '/meals', to: 'meals#index', as: 'all_meals'
  resources :meals, only: [:index, :new, :create] do
    resources :awards, only: [:new,:create]
  end

  resources :restaurants do
    get '/map', to: 'restaurants#map'
    resources :meals do
      resources :awards, only: [:new, :create, :edit, :patch]
    end
  end

end

app/views/shared/_filter-bar.html.erb
<div class="filter-bar">

  <div class="filter-bar-tags">

  <!--   <div class="filter-bar-tags-meals">
         <%#= form_tag all_meals_path, method: :get do %>
      <%#= text_field_tag :searchquery, params[:searchquery], placeholder: "Barcelona", class: "form-control", id: 'searchbar' %>
      <#% end %>
    </div> -->
    <div>
      <div class="fake-form">
       <i class="fas fa-map-pin" style="font-size: 10px; color: grey;" ></i> Barcelona
      </div>
    </div>

    <div class="filter-bar-tags-meals">
      <%= form_tag all_meals_path, method: :get do %>
      <%= text_field_tag :searchquery, params[:searchquery], placeholder: "Search", class: "form-control", id: 'searchbar' %>
     <% end %>
    </div>
  </div>

  <div class="filter-bar-map">
    <% if params[:category_id].present? %>
      <%= link_to "", category_map_path(params[:category_id]), class: "far fa-map fa" %>
    <% elsif params[:id].present? %>
      <%= link_to "", restaurant_map_path(params[:id]), class: "far fa-map fa" %>
    <% elsif params[:searchquery].present? %>
      <%= link_to "", map_categories_path(params.permit!), class: "far fa-map fa" %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    <%= link_to "kecomo", root_path %>
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_map.html.erb
<div
  id="map"
  style="width: 100vw;
  height: 100vh;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/shared/_meal-card.html.erb
<div class="container">
  <% @meals.each_with_index do |meal, index| %>
    <br>
    <div class="row">
      <div class="card-meal">
        <% case index %>
        <% when 0 %>
          <div class="card-meal-rank-1">
            <%= index + 1 %>st
        <% when 1 %>
          <div class="card-meal-rank-2">
            <%= index + 1 %>nd
        <% when 2 %>
          <div class="card-meal-rank-3">
            <%= index + 1 %>rd
        <% else %>
          <div class="card-meal-rank">
            <%= index + 1 %>th
        <% end %>
        </div>
        <!-- meal cloudinary image -->
        <div class="card-meal-photo-info">

  <% if meal.picture.blank? %>
    <%= link_to category_meal_path(meal.category_id, meal.id) do %>
      <%= image_tag "default-restaurant.png", class: "card-meal-no-image"%>
    <% end %>
  <% else %>
   <%= link_to category_meal_path(meal.category_id, meal.id) do %>
    <%= image_tag meal.picture %>
  <% end %>
  <% end %>

        <div class="card-meal-infos">
            <!-- meal.name -->
          <h2><%= link_to meal.name, category_meal_path(meal.category_id, meal.id) %></h2>
          <!-- meal.award.review -->
          <p><%= meal.description %></p>
          <div class="card-meal-button-wrapper">
            <div class="card-meal-restaurant-button">
              <!-- meal.restaurant -->
              <p><%= link_to meal.restaurant.name, restaurant_path(meal.restaurant) %></p>
            </div>
            <div class="card-meal-category-button">
              <!-- meal.category -->
              <p><%= link_to meal.category.name, category_meals_path(meal.category_id) %></p>
            </div>
          </div>
        </div>
      </div>

          <!-- Need to implement two differently styled buttons here -->
        <div class="card-meal-voting">
          <!-- checks if the user has already given award in this category -->
          <% if user_signed_in? && @current_user_awarded_categories.include?(meal.category) %>
          <!-- checks if the current user has any awards for the given meal -->
            <% if @current_user_awards.find_all { |award| award.meal == meal }.any?%>
            <!-- the user has given award in the category and one of the awards of this given meal belongs to the user, so the user has already awarded this meal, maybe a little info window/pop up to tell him about the obvious, Need to change the "upvote" to a different icon -->
              <div class="card-meal-vote-button">
                <%#= link_to new_restaurant_meal_award_path(meal.restaurant, meal), :data => {:confirm => 'You already awarded this item... Would you want to change your review?'} do %>
                <!-- # data: { confirm: 'You have already given your award in this category to this ....... Are you sure you want to change your vote?' } -->
                <%= image_tag "vote-pink.png", class: "card-meal-vote-img", data: { target: "#sameAwardModal-#{meal.id}", toggle: "modal"} %>
                <p style="text-align: center;"><%= meal.awards.count %> votes</p>
                <%# end %>
              </div>
            <% else %>
            <!-- checks if the user has already given award in this category and if the current meal has an award from the current_user-->
            <!-- the user has given award in the category but none one of the meal awards of this meal have been given by the user; the user has selceted another meal in this category, so can vote for this one, redirect to new award but give him a pop up notice about the fact that he is changing the award in the given already category -->
              <div class="card-meal-vote-button">
                <%#= link_to 'Upvote', new_restaurant_meal_award_path(@meal.restaurant, @meal), :data => {:confirm => 'Are you sure? You have already given an award to a meal in this category. So, by doing this you will be replacing your #1'} %>
                  <%= image_tag "vote.png", class: "card-meal-vote-img", data: { target: "#replaceAwardModal-#{meal.id}", toggle: "modal"} %>
                  <p style="text-align: center;"><%= meal.awards.count %> votes</p>
              </div>
            <% end %>
            <!-- if the user has NOT yet given award in this category(same as the buttons above, just no pop-up that warns about the category being awarded by the user) or the user is not yet signed in -->
          <% else %>
            <div class="card-meal-vote-button">
              <%#= link_to new_restaurant_meal_award_path(@meal.restaurant, @meal) do %>
                <%= image_tag "vote.png", class: "card-meal-vote-img", data: { target: "#firstAwardModal-#{meal.id}", toggle: "modal"} %>
                <p style="text-align: center;"><%= meal.awards.count %> votes</p>
              <%# end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <!-- Modals -->
    <!-- sameAwardModal -->
    <div class="modal fade" id="sameAwardModal-<%= meal.id %>" tabindex="-1" role="dialog" aria-labelledby="sameAwardModal" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><strong>Best <%= meal.category.name %> in <%= meal.restaurant.city %></strong></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="choose-details">
              <h4><i class="fas fa-exclamation-triangle"></i> Seems that you have already voted for this meal</h4>
              <div class="row-vote">
                <h3><%= meal.name %></h3>
                <h2>from</h2> <h3><%= meal.restaurant.name %></h3>
                <h2>is currently your best</h2> <h3><%= meal.category.name %></h3>
                <h2>in</h2> <h3><%= meal.restaurant.city %></h3>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- replaceAwardModal -->
    <div class="modal fade" id="replaceAwardModal-<%= meal.id %>" tabindex="-1" role="dialog" aria-labelledby="replaceAwardModal" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><strong>Best <%= meal.category.name %> in <%= meal.restaurant.city %></strong></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="choose-details">
              <h4><i class="fas fa-exclamation-triangle"></i> You have already voted for a meal in this category</h4>
              <div class="row-award">
                <h1>You only have one vote for each category, so choose wisely!</h1>
              </div>
              <div class="row-vote">
                <h2>You are about to vote for</h2>
                  <h3><%= meal.name %></h3>
                  <h2>at</h2> <h3><%= meal.restaurant.name %></h3>
                  <h2>as the best</h2> <h3><%= meal.category.name %></h3>
                  <h2>in</h2> <h3><%= meal.restaurant.city %></h3>
              </div>
              <div class="user-thing">
                <%# @meal = meal %>
                <%# @award = Award.new %>
                <%= simple_form_for [meal,@award] do |f| %>
                  <%= f.input :photo, :label => "- Upload a photo (optional)" %>
                  <%= f.input :photo_cache, as: :hidden %>
                  <%= f.input :review, :label => "- Tell us how much you like it! (optional)", as: :text, class: "review" %>
                  <%= f.submit "Confirm", class: "btn btn-info" %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- firstAwardModal -->
    <div class="modal fade" id="firstAwardModal-<%= meal.id %>" tabindex="-1" role="dialog" aria-labelledby="firstAwardModal" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><strong>Best <%= meal.category.name %> in <%= meal.restaurant.city %></strong></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="choose-details">
              <div class="row-award">
                <h1>You only have one vote for each category, so choose wisely!</h1>
              </div>
              <div class="row-vote">
                <h2>You are about to vote for</h2>
                  <h3><%= meal.name %></h3>
                  <h2>at</h2> <h3><%= meal.restaurant.name %></h3>
                  <h2>as the best</h2> <h3><%= meal.category.name %></h3>
                  <h2>in</h2> <h3><%= meal.restaurant.city %></h3>
                </h2>
              </div>
              <div class="user-thing">
                <%# @meal = meal %>
                <%= simple_form_for [meal,@award] do |f| %>
                <%= f.input :photo, :label => "- Upload a photo (optional)" %>
                <%= f.input :photo_cache, as: :hidden %>
                <%= f.input :review, :label => "- Tell us how much you like it! (optional)", as: :text, class: "review" %>
                <%= f.submit "Confirm", class: "btn btn-info" %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="nav-left-icons">
    <%= link_to "", "javascript:history.back()", class: "fas fa-angle-left" %>
    <%= link_to "", root_path, class: "fas fa-home" %>
  </div>

  <% if user_signed_in? %>
  <!-- Right Navigation -->
    <div class="navbar-wagon-right">
      <p><%= link_to "Don't see your meal?", new_meal_path %></p>

      <!-- Profile picture with dropdown list -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.picture == nil %>
            <%= image_tag "blank-avatar.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", data: { toggle: "dropdown" } %>
          <% else %>
            <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", data: { toggle: "dropdown" } %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Profile", profile_path(current_user), class: "dropdown-item" %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
          </ul>
        </div>
      </div>
    </div>
  <% else %>
    <div class="list-inline tabs-underlined">
      <p><%= link_to "Don't see your meal?", new_meal_path, class: "tab-underlined" %></p>
      <p><%= link_to "Log in", new_user_session_path, class: "tab-underlined" %></p>
    </div>
  <% end %>
</div>

app/views/shared/_navbar_transparent.html.erb
<div class="navbar-wagon-transparent">
  <!-- Logo -->
  <%= link_to image_tag("kecomo-logo.png"), root_path, class: "kecomo-logo" %>

  <% if user_signed_in? %>
  <!-- Right Navigation -->
    <div class="navbar-wagon-right">

      <!-- Profile picture with dropdown list -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.picture == nil %>
            <%= image_tag "blank-avatar.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", data: { toggle: "dropdown" } %>
          <% else %>
            <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", data: { toggle: "dropdown" } %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Profile", profile_path(current_user), class: "dropdown-item" %></li>
            <li><%= link_to "Don't see your meal?", new_meal_path, class: "dropdown-item" %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
          </ul>
        </div>
      </div>
    </div>
  <% else %>
    <div class="list-inline tabs-underlined">
      <p><%= link_to "Log in", new_user_session_path, class: "tab-underlined" %></p>
    </div>
  <% end %>
</div>

app/views/shared/_search-bar.html.erb
<div action="" id="search-bar" class="form-inline">
  <%= form_tag all_meals_url, style: "display: flex", method: :get do %>
    <%= text_field_tag :searchquery, params[:searchquery], placeholder: "Try 'Pizza Market' or 'Pizza'", class: "form-control", id: 'searchbar' %>
    <button type="submit" name="commit" value="search" class="btn btn-info btn-fill">GO!</button>
  <% end %>
</div>