config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  get '/profile', to: 'pages#profile', as: 'profile'

  resources :awards, except: [:show]

  resources :categories, only: [:show] do
    collection do
      get 'map'
    end
    get '/map', to: 'meals#map'
    resources :meals, only: [:show, :index] do
      resources :awards, only: [:new, :create]
    end
  end

  get '/meals', to: 'meals#index', as: 'all_meals'
  resources :meals, only: [:index, :new, :create] do
    resources :awards, only: [:new,:create]
  end

  resources :restaurants do
    get '/map', to: 'restaurants#map'
    resources :meals do
      resources :awards, only: [:new, :create, :edit, :patch]
    end
  end

end

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content">
    <h2>Looking for the best voted food on the menu?</h2>
    <%= render 'shared/search-bar' %>
  </div>
</div>

<div class="container">
<h3>Discover the best food in town</h3>
  <div class="container-categories">
    <div class="row">
      <% @categories.each do |category| %>
        <div class="col-4 col-md-3">
          <div class="card">
            <div class="card-img">
              <%= link_to (image_tag (category.icon)), category_meals_path(category.id) %>
            </div>
            <div class="card-txt">
              <h5><strong><%= category.name %></strong></h5>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container">
  <div class="profile-user">
    <% if current_user.picture == nil %>
      <%= image_tag "blank-avatar.jpg", class: "avatar" %>
    <% else %>
      <%= image_tag current_user.picture, class: "avatar", id: "navbar-wagon-menu" %>
    <% end %>
    <h2><%= @user.first_name %> <%= @user.last_name %> </h2>
    <%= link_to edit_user_registration_path do %>
    <i class="fas fa-cog"></i>
    <% end %>
  </div>
  <div class="profile-header">
    <h1>My votes:</h1>
  </div>
  <div class="container">
    <% @awards.each_with_index do |award, index| %>
    <br>
    <div class="row">
      <div class="card-meal">
          <div class="card-meal-rank-1">
            1st
          </div>
        <!-- meal cloudinary image -->
        <div class="card-meal-photo-info">

          <% if award.meal.picture == nil || award.meal.picture == "" %>
            <%= link_to category_meal_path(award.meal.category_id, award.meal.id) do %>
              <%= image_tag "default-restaurant.png", class: "card-meal-no-image"%>
            <% end %>
          <% else %>
            <%= link_to category_meal_path(award.meal.category_id, award.meal.id) do %>
              <%= image_tag award.meal.picture %>
            <% end %>
          <% end %>
          <div class="card-meal-infos">
            <!-- meal.name -->
            <h2><%= link_to award.meal.name, category_meal_path(award.meal.category_id, award.meal.id) %></h2>
            <!-- meal.award.review -->
            <p style="font-style: italic;"><%= award.meal.description %></p>
            <div class="card-meal-button-wrapper">
              <div class="card-meal-restaurant-button" style="margin-right: 5px;">
                <!-- meal.restaurant -->
                <p><%= link_to award.meal.restaurant.name, restaurant_path(award.meal.restaurant) %></p>
              </div>
              <div class="card-meal-category-button">
                <!-- meal.category -->
                <p><%= link_to award.meal.category.name, category_meals_path(award.meal.category_id) %></p>
              </div>
            </div>
          </div>
        </div>
        <div class="profile-change-delete">
          <%  if user_signed_in? && award.user_id == current_user.id %>
          <%= link_to award_path(award), class: "color-edit-delete",:id=> "color-edit-delete", method: :delete,
          data: { confirm: 'You about to delete your vote for that meal.'} do %>
          <i class="far fa-trash-alt" id="color-edit-delete"></i>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  </div>
  </div>
</div>
</div>